#!/usr/bin/env node
// Builds the npm tarball, installs it somewhere clean, and runs the published
// binary the way `npx @toolstop/<server>` would.
//
// The npm package is half this project's distribution and none of it was
// covered. dist/ is generated by prepack at publish time and gitignored, so
// nothing in the repo is the artifact; the import rewrite that makes the tarball
// resolvable was proven only by prepack.mjs not throwing. A tarball missing its
// transport, or pointing at a `bin` that does not exist, would have published
// green and failed for the first person who installed it.
//
// This is deliberately an install, not a `node dist/index.mjs`. Running the file
// in place resolves through the repo and hides exactly the failure being tested.
//
// usage: node scripts/tarball-check.mjs <package-name>

import { execFileSync } from "node:child_process";
import { mkdtempSync, rmSync, readFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { openStdioServer, exerciseServer } from "./lib/stdio-client.mjs";

const pkg = process.argv[2];
if (!pkg) {
  console.error("usage: tarball-check.mjs <package-name>");
  process.exit(2);
}

const pkgDir = resolve("packages", pkg);
if (!existsSync(join(pkgDir, "package.json"))) {
  console.error(`No packages/${pkg}/package.json`);
  process.exit(2);
}

const manifest = JSON.parse(readFileSync(join(pkgDir, "package.json"), "utf8"));
const server = (await import(pathToFileURL(join(pkgDir, "tools.mjs")).href)).default;

const fail = (msg) => {
  console.error(`FAIL  ${msg}`);
  process.exit(1);
};
const ok = (msg) => console.log(`ok    ${msg}`);

const work = mkdtempSync(join(tmpdir(), "toolstop-tarball-"));
let client;

try {
  // npm pack runs the prepack hook, so this is the same dist/ that publish ships.
  // The hook prints to the same stdout as --json, so the report starts at the
  // first bracket rather than at the first byte.
  const packOutput = execFileSync(
    "npm",
    ["pack", "--pack-destination", work, "--json", "--silent"],
    { cwd: pkgDir, encoding: "utf8" },
  );
  const report = packOutput.slice(packOutput.indexOf("["));
  const tarball = join(work, JSON.parse(report)[0].filename);
  ok(`packed ${manifest.name}@${manifest.version}`);

  // A tarball that ships no bin cannot be run by any client, and a bin whose
  // target prepack did not copy fails only on someone else's machine.
  const binEntries = Object.entries(manifest.bin ?? {});
  if (binEntries.length === 0) fail("package.json declares no bin, so npx cannot start it");

  // A fresh tree with no relationship to this repo, so nothing resolves by
  // accident through the workspace.
  execFileSync("npm", ["init", "-y"], { cwd: work, stdio: "ignore" });
  execFileSync("npm", ["install", "--no-audit", "--no-fund", "--silent", tarball], {
    cwd: work,
    stdio: "inherit",
  });
  ok("installed into a clean tree");

  const installed = join(work, "node_modules", manifest.name);
  for (const [binName, binPath] of binEntries) {
    const target = join(installed, binPath);
    if (!existsSync(target)) {
      fail(`bin "${binName}" points at ${binPath}, which is not in the tarball`);
    }
  }
  // main is what `import "@toolstop/x"` resolves, and prepack copies files by an
  // explicit list, so a file added to the package but not to that list is
  // missing here and nowhere else.
  if (manifest.main && !existsSync(join(installed, manifest.main))) {
    fail(`main points at ${manifest.main}, which is not in the tarball`);
  }
  ok("declared entrypoints are present in the tarball");

  // The real test: run the installed binary as a subprocess and speak MCP to it.
  // This is the first thing in CI that executes the rewritten imports.
  const [, firstBin] = binEntries[0];
  const examplesByTool = new Map(
    server.tools.map((tool) => [tool.name, tool.examples?.[0]]).filter(([, e]) => e),
  );

  client = openStdioServer(process.execPath, [join(installed, firstBin)], { cwd: work });
  const { serverInfo, tools, called } = await exerciseServer(client, {
    examplesByTool,
    log: (line) => ok(line),
  });

  if (serverInfo.version !== manifest.version) {
    fail(`the tarball reports v${serverInfo.version} but package.json says v${manifest.version}`);
  }
  if (tools.length !== server.tools.length) {
    fail(`the tarball exposes ${tools.length} tools, the definition has ${server.tools.length}`);
  }

  // Answers, not just responses. A tarball that imported a stale copy of the
  // library would still respond to every call.
  for (const { tool, result } of called) {
    const expected = examplesByTool.get(tool)?.expect ?? {};
    for (const [key, want] of Object.entries(expected)) {
      const got = result.structuredContent?.[key];
      if (JSON.stringify(got) !== JSON.stringify(want)) {
        fail(`${tool} returned ${key}=${JSON.stringify(got)}, expected ${JSON.stringify(want)}`);
      }
    }
  }
  ok("every tool returned the answer its example declares");

  console.log("\ntarball check passed");
} catch (err) {
  // A tarball that cannot start throws out of the client rather than reaching a
  // fail() call, and an unhandled rejection buries the reason under a stack.
  fail(err.message);
} finally {
  await client?.close();
  rmSync(work, { recursive: true, force: true });
}
